# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "11feaacaf327f4ed3b165975fb34ae3c"
name = "UpScroll – Scroll to Top"
application_url = "https://cs-scroll-to-top-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [
  "https://cs-scroll-to-top-production.up.railway.app/auth/callback",
  "https://cs-scroll-to-top-production.up.railway.app/auth/shopify/callback",
  "https://cs-scroll-to-top-production.up.railway.app/api/auth/callback"
]
